name: CI (UV + Pytest)

on:
  push:
    branches: [ main, "feat/**", "fix/**", "chore/**", "test/**" ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Create venv and install dependencies
        run: |
          uv venv .venv
          . .venv/bin/activate
          uv pip install -r requirements.txt
          uv pip install pytest-cov

      - name: Run tests
        run: |
          . .venv/bin/activate
          uv run -- pytest -q

      - name: Coverage (term + XML)
        run: |
          . .venv/bin/activate
          uv run -- pytest --cov=src --cov=main.py --cov-report=xml --cov-report=term-missing

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
